//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeptStores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class store
    {
        public int Id { get; set; }
        public string Picture { get; set; }

        [Display(Name = "Name of Store")]
        [Required(ErrorMessage = "Name of store is required!"), StringLength(30, MinimumLength = 1, ErrorMessage = "Name must be between 1 and 30 characters in length!")]
        public string Name { get; set; }

        [Display(Name = "Main Location")]
        [Required(ErrorMessage = "The Location is required"), StringLength(30, MinimumLength = 2, ErrorMessage = "Location must be between 2 and 30 characters in length!")]
        public string Location { get; set; }

        [Display(Name = "About the Store")]
        [Required, StringLength(500, MinimumLength = 10, ErrorMessage = "Description must be between 10 and 500 characters in length!")]
        public string Description { get; set; }

        public int? Likes { get; set; }
        public int? Dislikes { get; set; }

        [Display(Name = "Visits per year")]
        [DisplayFormat(DataFormatString = "{0:0,0}")]
        [Range(1, 100000000, ErrorMessage = "Please ensure the number you enter is between 1 and 100 000 000!")]
        public int Visitors_Frequency { get; set; }

        [Display(Name = "Yearly profit")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Range(1, 10000000000, ErrorMessage = "Please ensure the number you enter is between 1 and 10 000 000 000!")]
        public int Profit_Yearly { get; set; }

        [Display(Name = "Number of stores")]
        [Range(1, 10000, ErrorMessage = "Please enter a number between 1 and 1000")]
        public int Number_of_stores { get; set; }

        [Display(Name = "Added by")]
        [Required(ErrorMessage = "Your name is required"), StringLength(10, MinimumLength = 2)]
        public string Added_by { get; set; }

        [Display(Name = "Date created")]
        public DateTime Created_Date { get; set; }

        [Display(Name = "Date modified")]
        public DateTime Modified_Date { get; set; }

        [Display(Name = "Picture courtesy of")]
        public string Pic_Courtesy_of { get; set; }
    }
}
